name: bytelearn_study_tracker
description: "A Flutter mobile application for students to track study sessions, projects, and goals."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State management
  provider: ^6.1.1
  
  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^4.4.0
  
  # UI components
  flutter_svg: ^2.0.10+1
  intl: ^0.19.0
  
  # Charts for statistics
  fl_chart: ^0.70.0
  
  # App info and external links
  package_info_plus: ^6.0.0
  url_launcher: ^6.2.5
  
  # Timer functionality
  wakelock: ^0.6.2
  vibration: ^1.8.4
  flutter_local_notifications: ^16.3.2
  
  # Background execution
  workmanager: ^0.5.2
  shared_preferences: ^2.2.2
  
  # Animations and UI effects
  flutter_animate: ^4.5.0
  lottie: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Hive generators
  build_runner: ^2.4.8
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/animations/
    - assets/sounds/
    - assets/images/
