// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class FontRes {
  FontRes._();

  static const String PROJECT_NAME = 'study';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String PLUSJAKARTASANS_BOLD = 'PlusJakartaSans-Bold';
  static const String PLUSJAKARTASANS_MEDIUM = 'PlusJakartaSans-Medium';
  static const String PLUSJAKARTASANS_REGULAR = 'PlusJakartaSans-Regular';
  static const String PLUSJAKARTASANS_SEMIBOLD = 'PlusJakartaSans-SemiBold';
}
