// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Firebase configuration for Project Atlas (study-tracker-abdb2)
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxEZesHHtm0lc1ytd9y5ifrb3VuIpiPAw',
    appId: '1:1001014195663:web:16847b0bdbc9a58675ceba',
    messagingSenderId: '1001014195663',
    projectId: 'study-tracker-abdb2',
    authDomain: 'study-tracker-abdb2.firebaseapp.com',
    storageBucket: 'study-tracker-abdb2.firebasestorage.app',
    measurementId: 'G-DLKYWV3LGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxEZesHHtm0lc1ytd9y5ifrb3VuIpiPAw',
    appId:
        '1:1001014195663:android:16847b0bdbc9a58675ceba', // This may need to be updated if you add Android app
    messagingSenderId: '1001014195663',
    projectId: 'study-tracker-abdb2',
    storageBucket: 'study-tracker-abdb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxEZesHHtm0lc1ytd9y5ifrb3VuIpiPAw',
    appId:
        '1:1001014195663:ios:16847b0bdbc9a58675ceba', // This may need to be updated if you add iOS app
    messagingSenderId: '1001014195663',
    projectId: 'study-tracker-abdb2',
    storageBucket: 'study-tracker-abdb2.firebasestorage.app',
    iosBundleId: 'com.example.studytrackermobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxEZesHHtm0lc1ytd9y5ifrb3VuIpiPAw',
    appId: '1:1001014195663:ios:16847b0bdbc9a58675ceba',
    messagingSenderId: '1001014195663',
    projectId: 'study-tracker-abdb2',
    storageBucket: 'study-tracker-abdb2.firebasestorage.app',
    iosBundleId: 'com.example.studytrackermobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxEZesHHtm0lc1ytd9y5ifrb3VuIpiPAw',
    appId: '1:1001014195663:web:16847b0bdbc9a58675ceba',
    messagingSenderId: '1001014195663',
    projectId: 'study-tracker-abdb2',
    authDomain: 'study-tracker-abdb2.firebaseapp.com',
    storageBucket: 'study-tracker-abdb2.firebasestorage.app',
  );
}
